### ISSUE TITLE
[EASY | MEDIUM | HARD] The Monolithic Static Analysis Thread

### ISSUE THREAD

**Issue by flibitijibibo** [flibitijibibo/FNA#196]
Difficulty: This task contains many individual subtasks that vary in difficulty, ranging from EASY to HARD. Pick any task you want, based on what you think you can do correctly in a short period of time.

This is so overdue that it hurts.

We can think we're sooo cool for having a cleaned up version of the code, but that doesn't matter if the actual code doesn't work very well. We're down to 0 compiler warnings, but that doesn't mean a whole lot... especially when static analysis enters the ring!

This will act as the monolithic thread for bringing our static analysis warnings down to 0, for ALL possible analyzers. For starters, here are our current reports:

Gendarme: http://www.flibitijibibo.com/fna/gendarme.html
VS /analyze (includes third-party libs, ignore these warnings): [Spreadsheet](https://docs.google.com/spreadsheets/d/1BEYIIBYKOsmbV3mScPcDnFZTHa85c1tyXP5WJMwqlM4/edit#gid=1973671232&vpid=A2)

The Utilities/ folder is the only folder that is NOT to be touched. This is because we need to keep MonoGame compatibility for these files in particular. In addition, we will NOT be touching the StockEffects since those came directly from Microsoft, so changing them would only be more inaccurate.

If you have other static analysis tools, please run FNA through them and send me the results. In particular, I'd love to have results from the Visual Studio /analyze tool.

For this task, simply take any task in the report you want (letting us know you're doing so), send me the PR to fix it, and I'll update the report.

Ideally we should be able to properly fix all of these defects, but some are by XNA4's design... for example, Microsoft.Xna.Framework.Input.Touch is a massive namespace, and Gendarme reports this, but we can't change this without breaking XNA4 compatibility. In these situations, add a line to suppress the warning and document why the suppression is needed.

As we get closer to resolving all the warnings I'll be lowering the threshold for warning level and certainty, so expect more defects to show up as the list gets smaller.

This is our current list of analyzers:

- Gendarme: http://mono-project.com/Gendarme
- Coverity: https://scan.coverity.com/projects/flibitijibibo-fna
- Visual Studio /analyze (NEEDS UPDATE) - Courtesy of @willxinc

If you've got a new tool, please let us know!

If you decide to take a task, please post here and let us know you're working on it. Because we're doing so much work on so much code, we need to be sure we're not conflicting with other branches. Be sure to check ALL [FNA] issues before taking on a task!

**Comment by flibitijibibo** [comment]
With the Effect rewrite now in `master`, all folders except Utilities/ are now open for this task.

**Comment by flibitijibibo** [comment]
While updating the Gendarme report today I removed the /analyze report, since it's almost a year old. If anyone has this tool, a new report would be great.

**Comment by willxinc** [comment]
This what you're looking for?
https://gist.github.com/willxinc/cb8d96f68f0d2c0d72d0

or for a more readable version of the full one:

https://docs.google.com/spreadsheets/d/1iv5PDbqW65d_9QMeWQ_Sac4u2kgMwOcIxchE7J8nIqg/edit#gid=744026683

**Comment by flibitijibibo** [comment]
Wow, this is great! That's exactly what I'm looking for (and a whole lot more, too!). Will update the OP with this info.

**Comment by willxinc** [comment]
In the spreadsheet, I've filtered out all the common name warnings (CA1702, CA1704, CA1707, CA1709) errors.
Leaving you with 3934 warnings out of the original 12380.
Should I set it to public edit access?

**Comment by flibitijibibo** [comment]
I wouldn't worry about edit access - we may add some ignore rules like we did with Gendarme, but that can be figured out as we start going through the actual errors. The only ones we can cut out immediately are any errors involving the third-party libs (SDL2#, OpenAL#, etc.), though the rest might be worth looking at.

Sometimes we can't change a "bug" due to XNA4 spec, but sometimes XNA4 problems get mixed in with problems on our end that we can fix. This happens pretty frequently with things we get directly from Microsoft, like the errors we get in StockEffects despite it being the exact code they shipped in their example sources.

**Comment by willxinc** [comment]
The Community Edition should be identical to Pro, which includes the static code analysis feature.

**Comment by flibitijibibo** [comment]
The Gendarme results have been updated, and the current build is in Coverity's queue now.

FNA's first release is scheduled to be in mid-to-late December, so if anyone wants to burn through some issues before then, go for it.

**Comment by willxinc** [comment]
Updated the Visual Studio's Code Analysis spreadsheet by running Visual Studio 2015's Code Analysis on  on commit ba5e117:
https://docs.google.com/spreadsheets/d/1BEYIIBYKOsmbV3mScPcDnFZTHa85c1tyXP5WJMwqlM4/edit?usp=sharing

I removed the out / ref rule (to match Gendarme, CA1021, CA1045) as well as the underscores in names and identifier case rules (CA1707, CA1709).
Also filtered out all the warnings that were in ..\lib\* although some warnings don't have paths for some reason (done manually using google spreadsheets).

**Comment by flibitijibibo** [comment]
Beautiful, thanks. I've updated the OP with the new spreadsheet.

**Comment by flibitijibibo** [comment]
This issue has been discontinued in favor of the new repository:

https://github.com/FNA-XNA/FNA/issues/1
