### ISSUE TITLE
[XACT] Cue.Dispose Leak

### ISSUE THREAD

**Issue by tomspilman** [flibitijibibo/FNA#253]
I noticed that in `Cue.Dispose()`...

 https://github.com/flibitijibibo/MonoGame/blob/monogame-sdl2/MonoGame.Framework/Audio/Cue.cs#L202

... you never remove the `Cue` from the `AudioCategory`.  This means any `Cue` that is disposed by the user remains in the category.  This then affects the instance limits and in the single instance case keeps the cue from ever playing again.

**Comment by flibitijibibo** [comment]
I just attempted a fix at this:

https://github.com/flibitijibibo/FNA/commit/1309bd97a58f4987e06b04d4e12492400475ca1c

Let me know if it gets it. I swear I had this weird problem at one point where an AudioCategory `foreach` was getting blown up my something related to this, but it was at a point where it made no sense... when I do the playback rewrite I should probably be more conscious of when things are getting moved around in the engine.

**Comment by nickgravelyn** [comment]
Definitely seems to have fixed it. I took out my calls to Stop() and I was able to change songs in my game again. Haven't extensively tested to see if there are side effects, though.

**Comment by flibitijibibo** [comment]
I'll mark this as fixed since this issue was only concerned with the leak, but if we find anything that's definitely a regression from this we can always tag the issue/commit again. Thanks to both of you for the report.
