### ISSUE TITLE
Content loading issue

### ISSUE THREAD

**Issue by Vodacek** [flibitijibibo/FNA#265]
When I try to load content files created in MonoGame content builder I got this exception:

Could not find ContentTypeReader Type. Please ensure the name of the Assembly that contains the Type matches the assembly in the full type name: Microsoft.Xna.Framework.Content.SpriteFontReader, MonoGame.Framework, Version=3.1.2.0, Culture=neutral, PublicKeyToken=null (Microsoft.Xna.Framework.Content.SpriteFontReader, MonoGame.Framework)

I got this error after updating to latest version.Any ideas?

**Comment by mispy** [comment]
I ran into this while trying to get Platformer2D from MonoGame.Samples running under FNA (as an intermediary step to using it for testing JSIL). Can confirm replacing MonoGame.Framework in the type strings works, at least for my case.
