### ISSUE TITLE
[MEDIUM] [GC] SpriteBatch.DrawString(StringBuilder) generates garbage

### ISSUE THREAD

**Issue by wanton7** [flibitijibibo/FNA#266]
You are probably aware of this issue already. But SpriteBatch DrawString with StringBuilder overload is just using ToString and is generating garbage.

**Comment by flibitijibibo** [comment]
I duplicated the Draw/Measure methods to avoid ToString(), if someone wants to try and unduplicate it they can.

https://github.com/flibitijibibo/FNA/commit/986fef0f19475de1488208c4a21fdcea03cd239c
