### ISSUE TITLE
System.NullReferenceException when trying to use Texture2D.FromStream() to load a png

### ISSUE THREAD

**Issue by CantStraferight** [flibitijibibo/FNA#278]
Copied the code from an old XNA program so I'm pretty sure my code is correct.

This is on windows, not tried on Linux or OSX.

Tried looking into it but this looks to be beyond me.  
The error is coming from line 562 of texture2D.cs

**Comment by flibitijibibo** [comment]
What does SDL_GetError() report after this line?

https://github.com/flibitijibibo/FNA/blob/master/src/Graphics/Texture2D.cs#L510

**Comment by CantStraferight** [comment]
I was missing libpng16-16.  Got it working now.  Thanks
