### ISSUE TITLE
Cue.Dispose() doesn't decrement active cue count

### ISSUE THREAD

**Issue by nickgravelyn** [flibitijibibo/FNA#279]
During the move of Shipwreck over to the latest FNA I found that the XACT Audio Cue class doesn't properly decrement active instance counts in the audio category when you call Dispose(). I looked at it and it seems a fair bit of internal code assumes this is the case, thus managed cues call dispose during their update which breaks some for loops.

For now I'm just working around this by calling Stop() myself before calling Dispose(), but this is technically an incompatibility with XNA.

**Comment by nickgravelyn** [comment]
Oops, just realized this is a dupe of #253.

**Comment by flibitijibibo** [comment]
Pushed a possible fix to this, elaborated a bit more in the other issue:

https://github.com/flibitijibibo/FNA/commit/1309bd97a58f4987e06b04d4e12492400475ca1c
