### ISSUE TITLE
Looping SoundEffectInstances do not automatically play on Resume()

### ISSUE THREAD

**Issue by AxiomVerge** [flibitijibibo/FNA#291]
In XNA (as well as Monogame), I would typically create a looping sound effect instance, Pause() it immediately, and then, when I wanted to play it, call Resume().

In FNA, it appears necessary to call Play() before calling Resume().  For example,

```C#
mSoundEffect = content.Load<SoundEffect>("Audio/SoundEffects/" + name);
SoundEffectInstance instance = mSoundEffect.CreateInstance();
instance.IsLooped = true;
instance.Pause();
instance.Play();     //Required in FNA but not XNA or Monogame
instance.Resume();  //Used to be all that was needed to play a looped SoundEffectInstance
```

This is not a critical issue for me but it would be good to have the behavior match XNA for others newly porting their projects over.

**Comment by flibitijibibo** [comment]
This should be fixed, let me know if it isn't:

https://github.com/flibitijibibo/FNA/commit/b4f462ca1e390ef0f40fc4ee84e4ac138a1e684e
