### ISSUE TITLE
SoundEffect.MasterVolume multiplies Song volume

### ISSUE THREAD

**Issue by AxiomVerge** [flibitijibibo/FNA#292]
In XNA and Monogame, MediaPlayer.Volume controls the overall volume of Songs while SoundEffect.MasterVolume controls the overall volume of sound effects.

In FNA it appears that SoundEffect.MasterVolume governs both, so there isn't a way to adjust the volume of sound effects separately from music.

So, for example, if in XNA you wanted to tone down sound effects but not music, you would do

```C#
SoundEffect.MasterVolume = 0.25f;
MediaPlayer.Volume = 1.0f;
```

However in FNA, the MediaPlayer is represented as a queue of sound effects, so you end up reducing the volume of songs as well.

You cannot work around this by increasing the MediaPlayer.Volume above 1 since it is clamped internally.

**Comment by flibitijibibo** [comment]
Looks like this little note finally matters:

https://github.com/flibitijibibo/FNA/blob/master/src/Audio/SoundEffect.cs#L46

Since we use a DynamicSoundEffectInstance internally for MediaPlayer as well, that might be a reason why some levels are off.

I'll look at this now.

**Comment by flibitijibibo** [comment]
We're going to be somewhat dastardly and do this for now:

https://github.com/flibitijibibo/FNA/commit/a3d9c3e71497eea250bb0dc6e5b23aed2a09ea19

It's a few extra bits of math in addition to the SFI multiplication of MasterVolume which _should_ balance out, but maybe there's a detail missing still. Let me know if there is.

**Comment by AxiomVerge** [comment]
It appears to work now!  Thanks!

**Comment by flibitijibibo** [comment]
Cool. Hopefully this will be one of many correct fixes from yesterday. (Thanks for all of the reports, btw! I usually have to forcefully squeeze these out of devs!)
