### ISSUE TITLE
No way to mark PNGs as Content (avoiding xnb).

### ISSUE THREAD

**Issue by Phrohdoh** [flibitijibibo/FNA#295]
When loading PNG files (to avoid the MGCP for reasons) I am given the exception message:

>Could not load Content/Sprites/hero.png asset as a non-content file!

IIRC the Content tag was used to tell XNA to convert png to xnb then copy the resulting file to the output directory for usage by the final assembly.

If I am missing something obvious here please feel free to let me know and close this immediately.

**Comment by flibitijibibo** [comment]
Going to go out on a limb: Is SDL2_image, libpng and zlib in your game's directory? For Linux only SDL2_image/libpng are required, and for OSX SDL2_image is self-contained.

**Comment by Phrohdoh** [comment]
The given (archived) libSDL2_image requires a system install of libSDL2_image, so I've done that.
I wasn't aware of needing zlib, I'll take a look into that.

**Comment by flibitijibibo** [comment]
Run the debugger through here: https://github.com/flibitijibibo/FNA/blob/master/src/Content/ContentManager.cs#L501

**Comment by Phrohdoh** [comment]
To be frank I'm not sure how one would do that but I have installed `zlib` via homebrew and have a `libz.1.2.8.dylib` which I imagine I can include and reference in the FNA.dll.config for OS X's zlib.dll.

Trying this now.

**Comment by Vodacek** [comment]
Error is hidden in your loading code:
 
Could not load Content/Sprites/hero.png asset as a non-content file!
 
Right way to do it is without file extension. :-)
 
______________________________________________________________
> Od: Taryn Hill <notifications@github.com>
> Komu: "flibitijibibo/FNA" <FNA@noreply.github.com>
> Datum: 25.02.2015 20:26
> Předmět: Re: [FNA] No way to mark PNGs as Content (avoiding xnb). (#295)
>
To be frank I'm not sure how one would do that but I have installed zlib via homebrew and have a libz.1.2.8.dylib which I imagine I can include and reference in the FNA.dll.config for OS X's zlib.dll.
Trying this now.

**Comment by Phrohdoh** [comment]
Ah @Vodacek thank you sir!
I did solve that problem but I have yet to get an image on screen (though this is my fault and not FNA's).

Closing this, thanks guys!
