### ISSUE TITLE
Error when creating a texture

### ISSUE THREAD

**Issue by Unit158** [flibitijibibo/FNA#296]
Texture = Texture2D.FromStream(game.GraphicsDevice, s);

This was the line in question, from SpriteSheet.cs of [Phrohdoh's OpenRPG](https://github.com/Phrohdoh/OpenRPG/)

https://github.com/Phrohdoh/OpenRPG/blob/9c823ea8fbae8d978ea792aa18ff9ee5b2bff867/Graphics/SpriteSheet.cs#L25

http://pastebin.com/HUb5mtpw

**Comment by Phrohdoh** [comment]
[The file at the specific commit.](https://github.com/Phrohdoh/OpenRPG/blob/9c823ea8fbae8d978ea792aa18ff9ee5b2bff867/Graphics/SpriteSheet.cs#L25)

**Comment by flibitijibibo** [comment]
Apparently your driver does not think GL_DEBUG_SEVERITY_NOTIFICATION_ARB is an enum. As the trace notes, you'll need to go to that line and comment the glDebugMessageControlARB call out. Not to worry - this is only a debug function. I'll try and rework that later today.

**Comment by flibitijibibo** [comment]
I moved the callback attachment to the end of that block, so while there is still a GL_INVALID_ENUM for drivers that don't support notifications, it shouldn't throw an Exception anymore.

https://github.com/flibitijibibo/FNA/commit/0a9eff3687aa90c84835372a4f48a0b34e172b20

**Comment by Phrohdoh** [comment]
Thanks for the quick fix @flibitijibibo.
