### ISSUE TITLE
Dubious crash

### ISSUE THREAD

**Issue by Unit158** [flibitijibibo/FNA#297]
http://pastebin.com/Xx0hnFtW

I'm not really sure what to say.
This happened on the same line as my previous error.

Running a Radeon HD 5570 with OpenGL 4.2

https://github.com/Phrohdoh/OpenRPG/blob/9c823ea8fbae8d978ea792aa18ff9ee5b2bff867/Graphics/SpriteSheet.cs#L25

**Comment by flibitijibibo** [comment]
This looks like you're trying to perform GraphicsDevice operations before the GraphicsDeviceManager has been made. Have you tried this with XNA4?

I also notice that there are no lines for the FNA calls... are you building this in the solution, or using a DLL? Debugging will help when you're able to step through FNA in the debugger.

**Comment by flibitijibibo** [comment]
This is an OpenRPG bug:

https://github.com/Phrohdoh/OpenRPG/commit/2a1459cee3ba9a10436411fb9ad970c530634209

Undo this commit and you should be all set.

**Comment by Unit158** [comment]
Sorry for wasting your time ;-; Thanks anyway though.
