### ISSUE TITLE
BadFormatException on Windows 8.1.

### ISSUE THREAD

**Issue by Phrohdoh** [flibitijibibo/FNA#301]
Not sure what is causing this:
![image](https://static.dyp.im/7UBXhns5ex/large/dda3f71f088775bd2fe948882b11735f.PNG)

**Comment by flibitijibibo** [comment]
This typically happens when you try to load a 32-bit assembly from a 64-bit project.

**Comment by Phrohdoh** [comment]
The project is configured under Debug x86 so that should not be the issue, though I am very good at messing up csproj/sln build configurations.

**Comment by flibitijibibo** [comment]
I would refer to this then: http://stackoverflow.com/questions/8996653/troubleshooting-badimageformatexception

**Comment by Phrohdoh** [comment]
Unfortunately we have not been able to resolve this yet.
I will close it as soon as we figure it out, assuming it is still open then.

**Comment by flibitijibibo** [comment]
You may also want to directly reference FNA.csproj in your solution. Having a binary FNA.dll blob is not helpful for debugging anyway (which you should always be attempting to do as a programmer). This way you're not fighting binary blobs, since the libs were built by the exact same process as the one building your executables.

**Comment by Phrohdoh** [comment]
This forces my repository to be a full FNA tree on top of my project which is quite a bit of bloat.
Unless I am misunderstanding something.

**Comment by flibitijibibo** [comment]
If you feel that FNA is bloated, I invite you to work with smaller libraries like SDL2# directly.

Of course, you can also use Git submodules if needed:

http://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by Phrohdoh** [comment]
I've had troubles (irritations) with submodules in the past but it may be the best way, thank you for the suggestion.

I should be able to discuss this again with the team tomorrow and hopefully move forward from there provided submodule-ing FNA solves this issue.

**Comment by flibitijibibo** [comment]
Closing since this is more of a generic C# assembly compatibility issue rather than an FNA-specific thing.

I'm sure a lot of Visual Studio users would like to know an answer to this, though.
