### ISSUE TITLE
GamePadState.Triggers.Right and GamePadState.Triggers.Left occasionally initialize to 0.5

### ISSUE THREAD

**Issue by AxiomVerge** [flibitijibibo/FNA#304]
This is an intermittent issue I've noticed; once the game starts up and I haven't yet depressed either trigger on the 360 controller, the values read 0.5f - at least, until I press a trigger.  Then they seem to reset back to 0.

It's intermittent, so, I thought it could be an uninitialized variable or the like on the c++ side.

This is what I'm doing to read the state:

```C#
mGamePadState = GamePad.GetState(PlayerIndex.One, GamePadDeadZone.Circular);

//...Unrelated stuff here

mDrillPress = mGamePadState.Triggers.Right;

```

**Comment by flibitijibibo** [comment]
It might be uninitialized data, not sure. Have a look at this block in particular:

https://github.com/flibitijibibo/FNA/blob/master/src/SDL2/Input/SDL2_GamePad.cs#L783

The bits we care about are the axis values, which look like this on SDL's side:

https://hg.libsdl.org/SDL/file/537881242756/src/joystick/SDL_gamecontroller.c#l947
https://hg.libsdl.org/SDL/file/537881242756/src/joystick/windows/SDL_xinputjoystick.c#l249

The latter link is how the XInput state is updated... maybe it's something in this block? I bet that somewhere it starts as 0.5 to be neutral, but the XInput packet needs to be >0 before it can say that it's not in the "center":

https://hg.libsdl.org/SDL/file/537881242756/src/joystick/windows/SDL_xinputjoystick.c#l288

So maybe try starting the game up with the trigger fully pressed and see if it still says 0.5 before releasing it? (Though keeping a consistent trigger value is hard with this gamepad...)

**Comment by flibitijibibo** [comment]
I just spoke with Edward and it looks like this is a known multiplat issue with SDL:

https://bugzilla.libsdl.org/show_bug.cgi?id=2950

I would imagine he's right, so for kicks: In your Main() routine, add this block:

```
SDL2.SDL.SDL_SetHint(
    SDL2.SDL.SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS,
    "1"
);
```
Technically if you wanted to you could turn this back to "0" after the game's been started, but this depends on whether or not you'd like to have controller events happen outside of focus.

**Comment by AxiomVerge** [comment]
It's working so far.  In fact I probably want this code anyway as it's the behavior of XNA (it's quite handy I find to be able to move your character when your focus is in the debugger, too)

**Comment by flibitijibibo** [comment]
Ah, so that's XNA behavior? Very well, that's our behavior then! :)

https://github.com/flibitijibibo/FNA/commit/a3221bfb243504d125471e95b9e8c4b69cad9a39

**Comment by flibitijibibo** [comment]
Testing locally this seems to be fixed, so I'll close this for now. If it turns out I'm wrong, let me know!
