### ISSUE TITLE
GraphicsDeviceManager never set in Game

### ISSUE THREAD

**Issue by renaudbedard** [flibitijibibo/FNA#318]
The _graphicsDeviceManager field of Game is never set, and so the GLDevice is never disposed from the Game's Dispose() method (and subsequent dispose chain).

I'm not sure how it's supposed to grab it though?

**Comment by flibitijibibo** [comment]
Whuh, was checking the wrong service:

https://github.com/flibitijibibo/FNA/commit/f65ebc77400e1f1fb018633b0742147d79bae4e8

Should be fixed now.
